### ISSUE TITLE
User stories!

### ISSUE THREAD

**Issue by liaujianjie** [CS2103-AY1819S1-F10-3/main#1]
### Dump your ~ideas~ user stories here in the comments! 🔥🔥🔥

As a `<type of user>`, I want `<some goal>` so that `<some reason>`.

![flying doggo](https://media.giphy.com/media/SRx5tBBrTQOBi/giphy.gif)

**Comment by NightYeti** [comment]
As discussed, the app will be targeting call center staff. General idea is that the staff will use this address book as a database, and can look for customer's information and provide services to them accordingly.

**Comment by NightYeti** [comment]
Idea #1:
Staff login with their credential. Staff are given privilege access according to their jobscope. E.g. some staff are only able to view certain info about customers, while some other may view more info of customers related to their jobscope.

**Comment by NightYeti** [comment]
Idea 2:
Have a import option from files such as xml or excel, and read these data into the app, creating/editing customers entries.

**Comment by dongsiji** [comment]
Idea 3:
Search function not just limited to name, maybe other details that are important, email, number etc
Live searching?

**Comment by liaujianjie** [comment]
Idea 4:
Use rich forms instead of a CLI to manipulate contact information.

**Comment by liaujianjie** [comment]
Idea 5:
N-gram search

**Comment by eehooi** [comment]
Idea 6:
Delete contacts in bulk as call centers have many clients and contacts need not be required after a contract ends.

**Comment by wailunlim** [comment]
Idea 7: For call centres, the information of the customers should be a top priority. Storage files containing the information of clients should be encrypted to prevent any unauthorised access. (this complements idea 1 too)

**Comment by dongsiji** [comment]
Idea 6a:
Additional information stored on customers are needed i.e. contract start and end dates. To enable such a feature

**Comment by dongsiji** [comment]
Idea 8:
They can pickup calls using the CLI?

**Comment by wailunlim** [comment]
Idea 9: autocomplete + incremental search to improve the overall productivity.

**Comment by eehooi** [comment]
Idea 11:
Update if user has been called and when was the last call made so that they know whether they have to call again and when should the next call be scheduled. Implement in search feature.

**Comment by liaujianjie** [comment]
Post user stories as issues instead.
