### ISSUE TITLE
As an events manager, I want to be able to search the database and see the suppliers that best matches my requirements, so that I can find the most suitable suppliers for my clients.

### ISSUE THREAD

**Issue by dongsiji** [CS2103-AY1819S1-F10-3/main#2]
As an events manager, I want to be able to filter the database and see the suppliers that best matches my requirements, so that I can find the most suitable suppliers for my clients.

**Comment by liaujianjie** [comment]
I think "filter the database" seems a bit feature-specific. I suggest changing it to "search the contacts database" instead. What do you think?

**Comment by dongsiji** [comment]
yup sounds better that way
