### ISSUE TITLE
[P.E. Dry Run] automatch on non-existent serviceprovider results in both clients and serviceproviders being listed in the same list

### ISSUE THREAD

**Issue by adamwth** [CS2103-AY1819S1-F10-3/main#235]
serviceprovider#1 automatch
- Executing above command after deleting serviceprovider#1 (using serviceprovider#1 delete) results in
both clients and serviceproviders being listed in the same list on the left. This is unexpected behavior since one wouldn't expect to see both clients and serviceproviders being listed in the same list, given that the app is not an address book.

Apologies for posting directly on your issue tracker. I was having some trouble during the Dry Run yesterday and was not able to submit all my found issues to the Dry Run issue tracker. Prof has instructed me to post the issues I found directly on your issue tracker instead.

**Comment by liaujianjie** [comment]
Fixed with #277.
