### ISSUE TITLE
[BUG] Update command has a bug which results in data gone

### ISSUE THREAD

**Issue by NightYeti** [CS2103-AY1819S1-F10-3/main#305]
Lets say we have 2 entries,
Client 1: n/John Doe, p/98765432, e/john@example.com
Client 2: n/Jessica Lewis p/912345678 e/jessica@example.com

Normally when you execute `client#2 update n/John Doe p/98765432` it will throw a duplicate exception and feedback successfully, preventing the command from going through.

However, if you try
`client#2 update n/John Doe`
`client#2 update p/98765432`, the command will go through and not feedback as a duplicate. As a result, we now have 2 entries with the same name and phone number. When you exit the application and launching it again, all data will not be displayed as there is illegalArgumentFormat in reading the data, since no 2 client can possess the `same name && (either phone or email)`.

The behaviour is the same when in vendor context. Updating vendor in this manner results in the same buggy behaviour.

**Comment by wailunlim** [comment]
hehe
