### ISSUE TITLE
Icons and colours for documentation

### ISSUE THREAD

**Issue by liaujianjie** [CS2103-AY1819S1-F10-3/main#32]
Let's use icons and colours to semantically separate different types of content.

**Comment by NightYeti** [comment]
Yes, this will be desirable!

**Comment by liaujianjie** [comment]
## Proposal

### Tips `#1277D6`

![iconmonstr-info-6-48](https://user-images.githubusercontent.com/3143132/46336411-495eae00-c65d-11e8-951f-8d62bb662bb2.png)

For short snippets of information that can provides additional value to the user. Example: shortcut keys, better workflows

### Notes `#419871`

![iconmonstr-note-14-48](https://user-images.githubusercontent.com/3143132/46336413-4bc10800-c65d-11e8-8d95-2e30fee69f2c.png)

For details explanations of features or application behaviour.

### Danger `#FC433E`

![iconmonstr-warning-8-48](https://user-images.githubusercontent.com/3143132/46336416-4d8acb80-c65d-11e8-999b-d143b66badc2.png)

For messages requiring immediate user attention. Example: irreversible actions, security information

### Advanced `#ED25BC`

![iconmonstr-gear-2-48](https://user-images.githubusercontent.com/3143132/46336423-511e5280-c65d-11e8-971e-27fadd1753f5.png)

For details or instructions for technically-deep content.
