### ISSUE TITLE
As a client, I want to have a ratings system for the suppliers that I have employed, so that I can provide feedback for future users.

### ISSUE THREAD

**Issue by dongsiji** [CS2103-AY1819S1-F10-3/main#9]
As a client, I want to be able to rate the suppliers that I have employed, so that I can provide feedback for future users.

**Comment by liaujianjie** [comment]
"I want to have a ratings system" also seems a bit too feature-specific. What about "I want to be able to rate suppliers" instead? I think the rating system is a consequence of the desire to want to rate the supplier.

**Comment by dongsiji** [comment]
Ok I will edit the user story
